Add ADR for Code of Conduct
json-schema-org/community pull request #41
Opened 2021-08-26 15:21 UTC by Relequestual

Work required by https://github.com/json-schema-org/community/issues/26

2021-08-29 20:10 UTC, karenetheridge approved these changes

2021-08-31 17:49 UTC, jdesrosiers requested changes
Looks fine to me. However, as I read this, it occurs to me that it doesn't say much that isn't obvious, which leads me to wonder if it was really necessary for this to be an ADR.

ADRs are for us to come back years from now and be reminded of _why_ we made a decision, not what decision was made. The reasons for why to adopt a CoC are a bit obvious, but they are articulated well. However, I think we can do more to say _why_ we chose Contributor Covenant and BCP 54. For example,

* Why did we want to choose something established?
  * Because we don't have the experience to do something custom
  * Because we don't have community with unique needs that requires something custom
  * Because we can get feedback and learn from other projects that use the same CoC
  * Because people will feel more feel comfortable under a CoC they are familiar with from other communities
* Is BCP 54 just about treating people with respect? Do other parts of the document apply as well?
  * General consensus?

Again, most of that feels a little obvious to the point that I'm not sure it needs documenting, but if we're going to document it, we should be specific. If we have to read between the lines when we read this in the future, then it wasn't very useful.

2021-08-31 18:04 UTC, Julian commented
I think I agree strongly with that general point, though I'd also add that a secondary important thing to be able to look back on is purely that all of us have signed off on the change and put our name on it.

But I don't disagree with writing down as much info as we can about why we made a decision, and that if the decision is obvious, that maybe an ADR may not be needed.

(Also I suspect Ben's exercising his ADR muscles in part because we've just started using them :)

2021-09-03 09:15 UTC, Relequestual commented
I'll make some changes. Good call!

2021-09-23 17:11 UTC, Relequestual commented
If you can think of any more pros or cons, please make a suggestion in review to add them =]

2021-09-23 17:36 UTC, karenetheridge commented on docs/adr/2021-08-26-code-of-conduct.md
> +The Contributor Covenant is well established and regarded as a brilliant de-factor Code of Conduct option for open source projects.
brilliant? 🤮   how about "standard"

2021-09-24 09:48 UTC, Relequestual commented on docs/adr/2021-08-26-code-of-conduct.md
> +The Contributor Covenant is well established and regarded as a brilliant de-factor Code of Conduct option for open source projects.
I'll remove the word "briliant". "de-facto" already conveys standard, does it not?
(Also, outdated comment)

2021-09-28 21:07 UTC, jdesrosiers requested changes
lgtm. Just need to fix a minor typo.

2021-09-28 21:07 UTC, jdesrosiers commented on docs/adr/2021-08-26-code-of-conduct.md
> +* Good, because we have clear inforcement for conduct which covers the whole Code of Conduct
```suggestion
* Good, because we have clear enforcement for conduct which covers the whole Code of Conduct
```

2021-10-01 20:22 UTC, jdesrosiers approved these changes

2021-10-01 20:22 UTC, merged