Add Damodharan J as an ambassador
json-schema-org/community pull request #823
Opened 2024-11-07 09:33 UTC by damodharanj

Hello community,

These are my contributions and will also be giving a tech talk on ["JSONSchema - Runtime type-system"](https://confengine.com/conferences/functional-conf-2025/proposal/21044/jsonschema-as-runtime-type-system-from-full-stack-validation-to-structured-generation-in-llm). Looking forward to contribute as an ambassador. 

Please let me know if I have to do anything further.

2024-11-23 09:23 UTC, damodharanj commented
> Thanks a lot for your interest in becoming a JSON Schema Ambassador!! Your articles are very cool! I'll ask the TSC for their vote but you have mine.

Thanks a lot @benjagm! Looking forward!

2024-11-27 06:57 UTC, gregsdennis commented
I'm sorry for the delay.  I'd like to go through the articles, and I haven't had time.

2024-11-27 12:25 UTC, damodharanj commented
> I'm sorry for the delay. I'd like to go through the articles, and I haven't had time.

Hi @gregsdennis! Please look at the articles and if there are issues, just let me know anytime

2024-11-29 05:37 UTC, gregsdennis requested changes
The work you've submitted is impressive, but it's tightly coupled with a specific implementation and one that we typically recommend avoiding in favor of Jason's hyperjump.  (We recommend that if you use ajv, you do so only in "strict" mode to enforce compatibility.)

You've shown that you understand JSON Schema, which is great, but being an ambassador requires community involvement, which isn't something I've seen from you.

I'm sorry, but I can't approve this appointment at this time.

2024-11-29 07:08 UTC, damodharanj commented
Thanks a lot for the feedback @gregsdennis 🙂!

> The work you've submitted is impressive, but it's tightly coupled with a specific implementation and one that we typically recommend avoiding in favor of Jason's hyperjump. (We recommend that if you use ajv, you do so only in "strict" mode to enforce compatibility.)

Sure, have made the changes stating about "strict" mode as recommended usage mode. None of the examples require hyperjump.

> You've shown that you understand JSON Schema, which is great, but being an ambassador requires community involvement, which isn't something I've seen from you.

I m giving a tech talk on [JSONSchema as runtime typesystem](https://confengine.com/conferences/functional-conf-2025/proposal/21044/jsonschema-as-runtime-type-system-from-full-stack-validation-to-structured-generation-in-llm). 
The proposal accepted and will be a addressing a considerable amount of community

Also we have adopted JSONSchema in all of the stack (frontend & backend ) of [Phaged XPlain](https://phaged.in/) & 
hand-in-hand with LLMs to generate structured data. 

If there is anything else that would help me i would like try.

2024-12-02 18:20 UTC, jdesrosiers commented
> Sure, have made the changes stating about "strict" mode as recommended usage mode.

I think you've misunderstood. This is the line you added to your articles.

> Note: JSONSchema specification recommends using it [strict mode](https://ajv.js.org/strict-mode.html). Always use it strict mode to avoid un-intended behaviour.

The JSON Schema specification doesn't have a "strict mode". "Strict mode" is an ajv concept. By default, ajv violates the JSON Schema specification in several ways. In order to get fully JSON Schema compliant behavior when using ajv, you need to use ajv's strict mode.

So, for the articles that don't mention ajv, I suggest removing this note. For the articles that do mention ajv, please fix the note to make it clear this is an ajv problems, not a JSON Schema problem.

2024-12-03 05:46 UTC, damodharanj commented
> So, for the articles that don't mention ajv, I suggest removing this note. For the articles that do mention ajv, please fix the note to make it clear this is an ajv problems, not a JSON Schema problem.

Thanks a lot for the input. Have made the changes in the required articles.

2024-12-18 00:11 UTC, jdesrosiers commented
@damodharanj Someone brought up that there's still an issue with your ajv disclaimers. I think this is partially my fault due to a typo in my previous message. I even reviewed the changes and didn't notice that it was backwards.

**Strict mode in ajv is turned ON by default and must be turned OFF in order to be spec compliant.**

Please make the correction and I'm sorry for inadvertently telling you the wrong thing.

2024-12-18 06:26 UTC, damodharanj commented
> Please make the correction and I'm sorry for inadvertently telling you the wrong thing.

I have the made the changes about ajv in the relevant articles. Thanks for the headsup

2024-12-18 17:34 UTC, damodharanj commented
> Hey @damodharanj - The recommendation is to turn Strict Mode OFF. It is ON by default.
> When Strict Mode is ON, AJV is not compliant with the JSON Schema specification.

My bad. Oh got it now! I have made changes to the articles as per the suggestion. 

> Thanks for your articles and best of luck with your talk!

Thanks a ton @Relequestual ! Looking forward to presenting my experience working with JSONSchema and would share the feedback I get

2025-01-13 03:19 UTC, damodharanj commented
Hello all!
I implemented a shareable JSONSchema LLM Structured Outputs playground for my upcoming tech talk presentation
https://ai-schema-lab.phaged.in/
Features:
- Support for multiple LLM providers (OpenAI, Ollama)
- JSONSchema validation for structured outputs
- Shareable URLs with your prompt and schema
- Local API key storage
- Mobile-responsive design

Can I add this to this application as well ?

2025-02-03 07:54 UTC, damodharanj commented
Hello everyone - Here is the video of the talk I gave on ["JSONSchema as runtime typesystem"](https://www.youtube.com/watch?v=IdWMinvwFyc)

2025-06-28 13:18 UTC, benjagm commented
@damodharanj I hope this message finds you well. After a very long discussion we ran a [voting](https://github.com/json-schema-org/TSC/issues/21) round within the TSC and finally we decided to not accept the application. Do you have new materias we can consider in case we can ask the TSC again?

2025-07-17 08:32 UTC, benjagm commented
Closing this for now as the voting process already ended: https://github.com/json-schema-org/TSC/issues/21 

Thanks a lot for your interest and your contributions @damodharanj

2025-07-17 08:32 UTC, closed without merging

2025-07-17 15:32 UTC, damodharanj commented
> Closing this for now as the voting process already ended: [json-schema-org/TSC#21](https://github.com/json-schema-org/TSC/issues/21)
> 
> Thanks a lot for your interest and your contributions @damodharanj

Thanks a lot for the opportunity!